export const TABLE_DATA = {
  data: [
    {
      name: 'Courtney Henry',
      state: 'Lagos state',
      address: '775 Rolling Green Rd.',
      errorStatus: 'false',
      errorMessage: 'No issues',
      entries: '19 Unique Entries',
      type: 'Homogenous',
      riskLevel: 'Low risk',
    },
    {
      name: 'Darrell Steward',
      state: 'Lagos state',
      address: '7529 E. Pecan St.',
      errorStatus: 'true',
      errorMessage: '2 issues found',
      entries: '10 Unique Entries',
      type: 'Heterogenous',
      riskLevel: 'Mid risk',
    },
    {
      name: 'Cody Fisher',
      state: 'Lagos state',
      address: '3605 Parker Rd.',
      errorStatus: 'false',
      errorMessage: 'No issues',
      entries: '8 Unique Entries',
      type: 'Homogenous',
      riskLevel: 'Mid risk',
    },
    {
      name: 'Bessie Cooper',
      state: 'Lagos state',
      address: '775 Rolling Green Rd.',
      errorStatus: 'true',
      errorMessage: '1 issue found',
      entries: '12 Unique Entries',
      type: 'Heterogenous',
      riskLevel: 'High risk',
    },
    {
      name: 'Annette Black',
      state: 'Lagos state',
      address: '8080 Railroad St.',
      errorStatus: 'false',
      errorMessage: 'No issues',
      entries: '13 Unique Entries',
      type: 'Heterogenous',
      riskLevel: 'Low risk',
    },
    {
      name: 'Jenny Wilson',
      state: 'Lagos state',
      address: '8080 Railroad St.',
      errorStatus: 'true',
      errorMessage: '5 issues found',
      entries: '18 Unique Entries',
      type: 'Homogenous',
      riskLevel: 'High risk',
    },
    {
      name: 'Darlene Robertson',
      state: 'Lagos state',
      address: '3890 Poplar Dr.',
      errorStatus: 'true',
      errorMessage: '2 issues found',
      entries: '6 Unique Entries',
      type: 'Homogenous',
      riskLevel: 'Mid risk',
    },
    {
      name: 'Ralph Edwards',
      state: 'Lagos state',
      address: '8558 Green Rd.',
      errorStatus: 'false',
      errorMessage: 'No issues',
      entries: '14 Unique Entries',
      type: 'Homogenous',
      riskLevel: 'Low risk',
    },
  ],
};
